/*
 * This source file was generated by the Gradle 'init' task
 */
package org.lox;

import java.io.IOException;
import java.io.StringWriter;
import java.io.StreamTokenizer;

public class Lox {
  public String getGreeting() {
    return "Hello World!";
  }

  public String lol() {
    return "Lululull";
  }

  public static void main(String[] args) {
    System.out.println(new Lox().getGreeting());
  }
}
